"use client";

import { memo, useMemo, useState } from "react";
import type { TranscriptSection } from "@/lib/analysis/shared";
import { formatTimecode } from "@/lib/format";

export const TranscriptPanel = memo(function TranscriptPanel({ sections, start, end, ready, onSeek }: {
  sections: TranscriptSection[]; start?: number; end?: number; ready: boolean; onSeek: (time: number) => void;
}) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const cues = useMemo(() => {
    const unique = new Map<string, TranscriptSection["segments"][number] & { source: string }>();
    for (const section of sections) for (const cue of section.segments) {
      unique.set(`${cue.startSeconds}:${cue.text}`, { ...cue, source: section.source });
    }
    return [...unique.values()].sort((a, b) => a.startSeconds - b.startSeconds);
  }, [sections]);
  const matching = cues.filter((cue) => (!query || cue.text.toLowerCase().includes(query.toLowerCase()))
    && (start === undefined || end === undefined || (cue.endSeconds > start && cue.startSeconds < end)));
  return (
    <details className="mt-4 rounded-md border border-border bg-surface-raised p-3" onToggle={(event) => setOpen(event.currentTarget.open)}>
      <summary className="cursor-pointer text-xs font-medium">{start === undefined ? "Timestamped transcript" : "Transcript for selected clip"} · {matching.length} cues</summary>
      {open && <>
        <p className="mt-2 text-[11px] text-text-muted">Existing YouTube captions via Supadata. Captions may be auto-generated by YouTube and can contain errors; compare with playback.</p>
        <input aria-label="Search transcript" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Find words in the transcript…"
          className="mt-3 w-full rounded border border-border bg-bg px-3 py-2 text-xs outline-none focus:border-accent" />
        <ul className="mt-2 max-h-64 space-y-1 overflow-y-auto">
          {matching.slice(0, 150).map((cue, index) => <li key={index}>
            <button type="button" disabled={!ready} onClick={() => onSeek(cue.startSeconds)} className="flex w-full gap-3 rounded px-2 py-2 text-left text-xs hover:bg-surface-hover disabled:cursor-default">
              <span className="shrink-0 font-mono text-accent">{formatTimecode(cue.startSeconds)}</span><span className="text-text-muted">{cue.text}</span>
            </button>
          </li>)}
        </ul>
        {!matching.length && <p className="mt-3 text-xs text-text-muted">No transcript cues match this range or search.</p>}
        {matching.length > 150 && <p className="mt-2 text-[11px] text-text-muted">Showing the first 150 matching cues. Select a clip or search to narrow the transcript.</p>}
      </>}
    </details>
  );
});
